follow @jessfraz repo

diff --git a/.bash.d/functions b/.bash.d/functions
--- a/.bash.d/functions
+++ b/.bash.d/functions
@@ -43,26 +43,29 @@ function run_docker_tool {
    "docker-tools/$1" "$@"
 }
 
-command_not_found_handle() {
+# Checks that i'm not already in a container (cf. https://github.com/jessfraz/dotfiles/blob/master/.dockerfunc)
+if command -v "docker" &>/dev/null; then
+    command_not_found_handle() {
 
-  if [[ $(prompt_session_type) == "remote/docker" ]]; then
-    echo "$0: docker-tools/$1: command not found"
-    return
-  fi
+      #if [[ $(prompt_session_type) == "remote/docker" ]]; then
+      #  echo "$0: docker-tools/$1: command not found"
+      #  return
+      #fi
 
-  # echo docker inspect --format '{{ .Author }}' "docker-tools/$1"
-  # docker inspect --format '{{ .Author }}' "docker-tools/$1"
-  # Check if there is a container image with that name
-  if ! docker inspect --format '{{ .Author }}' "docker-tools/$1" >&/dev/null; then
-    echo "$0: docker-tools/$1: command not found"
-    return
-  fi
+      # echo docker inspect --format '{{ .Author }}' "docker-tools/$1"
+      # docker inspect --format '{{ .Author }}' "docker-tools/$1"
+      # Check if there is a container image with that name
+      if ! docker inspect --format '{{ .Author }}' "docker-tools/$1" >&/dev/null; then
+        echo "$0: docker-tools/$1: command not found"
+        return
+      fi
 
-  # Check that it's really the name of the image, not a prefix
-  if docker inspect --format '{{ .Id }}' "docker-tools/$1" | grep -q "^docker-tools/$1" ;then
-    echo "$0: docker-tools/$1: command not found"
-    return
-  fi
+      # Check that it's really the name of the image, not a prefix
+      if docker inspect --format '{{ .Id }}' "docker-tools/$1" | grep -q "^docker-tools/$1" ;then
+        echo "$0: docker-tools/$1: command not found"
+        return
+      fi
 
-  run_docker_tool $@;
-}
+      run_docker_tool $@;
+    }
+fi
